### ISSUE TITLE
Cannot publish with Nexus

### ISSUE THREAD

**Issue by rintcius** [sbt/sbt-unique-version#1]
publish-local works OK, but publish gives a "Bad Request". See log below.
Related forum post: https://groups.google.com/forum/#!topic/simple-build-tool/JSKFTZAUAGg

```
[info] :: delivering :: io.svc.mail#io-svc-mail_2.9.1;0.1-20120905-235028 :: 0.1-20120905-235028 :: integration :: Thu Sep 06 00:50:29 BST 2012
[info] Generating API documentation for main sources...
[info]  delivering ivy file to /var/lib/jenkins/jobs/io.svc.mail/workspace/target/scala-2.9.1/ivy-0.1-20120905-235028.xml
[info] Packaging /var/lib/jenkins/jobs/io.svc.mail/workspace/target/scala-2.9.1/io-svc-mail_2.9.1-0.1-SNAPSHOT.jar ...
[info] Done packaging.
model contains 13 documentable templates
[info] API documentation generation successful.
[info] Packaging /var/lib/jenkins/jobs/io.svc.mail/workspace/target/scala-2.9.1/io-svc-mail_2.9.1-0.1-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[error] {file:/var/lib/jenkins/jobs/io.svc.mail/workspace/}default-eac892/*:publish: java.io.IOException: PUT operation to URL http://localhost:8081/nexus/content/repositories/snapshots/io/svc/mail/io-svc-mail_2.9.1/0.1-20120905-235028/io-svc-mail_2.9.1-0.1-20120905-235028.pom failed with status code 400: Bad Request
```

**Comment by eed3si9n** [comment]
This was kind of an experimental plugin to target Ivy repos. If [sbt-aether-deploy](https://github.com/arktekk/sbt-aether-deploy) worked for Sonatype I'm closing this issue.

**Comment by rintcius** [comment]
Hmm, are you saying that you want this plugin to be superseded by sbt-aether-deploy? In that case, the fact that unique version is under https://github.com/sbt whereas sbt-aether-plugin is not, may give a wrong impression (it suggests to me that unique-version has a more "official" sbt status than sbt-aether-plugin)

Also note that there are features in this plugin that sbt-aether-deploy does not address, see e.g.
http://stackoverflow.com/questions/12213696/sbt-depend-on-specific-snapshot-version/12436938#12436938

Anyway, it may be good to state the intentions and restrictions on sbt-unique-version's main documentation page, possibly referring to sbt-aether-plugin.

**Comment by eed3si9n** [comment]
The first thing I wrote on the readme is:

> sbt-unique-version emulates Maven's uniqueVersion snapshots on Ivy repos.

Sonatype, since it's not an Ivy repo, is currently out of scope. I can make that more clear in the readme if you want.

As per plugin status, "sbt" github group is a community-run group that anyone can join in. Most of my plugins are under it so people can discover it, and also if someone wants to take over them the transition is transparent to the users.

**Comment by rintcius** [comment]
Yes, that sentence does not read to me as a restriction (sbt being a kind of wrapper around ivy)
I think it would be more clear if you phrase it something like this:

sbt-unique-version emulates Maven's uniqueVersion snapshots. It currently works only for Ivy repositories; Maven repositories are not supported.

Re sbt github group: ok, I will change my mindset about this ;)
