### ISSUE TITLE
Publish the plugin for SBT 0.13 final

### ISSUE THREAD

**Issue by pdalpra** [sbt/sbt-unique-version#3]
Hi, 

Looking at the scala-sbt plugins repo, the latest version of this plugin you published was for 0.13 Beta 2.
I'm all in for Josh's suggestion of using commit SHA's but unfornately, this would not play nicely when publishing to Maven repos, as Maven relies on timestamps.
Since your plugin allows to mimic Maven's unique versions, and SBT 0.13 final has been around for quite some time, It would be very nice if could publish a release of your plugin for SBT 0.13 final.

**Comment by eed3si9n** [comment]
Maven 1 - SHA-1 0 /cc @jsuereth 

I tried cross publishing it using sbt 0.13.2, and but it said the file is already there. Could you try now?
http://dl.bintray.com/sbt/sbt-plugin-releases/com.eed3si9n/sbt-unique-version/scala_2.10/sbt_0.13/0.1.0/jars/

**Comment by pdalpra** [comment]
Yep, and that's a pity, a SHA is much more informative than a timestamp !
Josh is aware of this problem, as I opened a issue on SBT to see if we can get SBT to mimic Maven's unique versions natively.

The plugin is loaded correctly by SBT, but this unfortunately doesn't work : as your plugin changes the module version, and not the artifact name, this made Nexus unhappy.
When I tried to publish snapshots for Gatling 2, SBT wanted to publish the artifacts to `oss.sonatype.org/.../gatling-xxx/2.0.0-20140515-222320/gatling-xxx-2.0.0-20140515-222320.jar`. And Nexus replied by a `400 Bad Request` :)

In this case, I think modifying the artifact name suffices.
I think I'll develop a SBT plugin to solve this very specific corner case of SBT/Maven interaction until SBT does it natively ;)

**Comment by eed3si9n** [comment]
O I should've read more carefully. This experimental plugin is intended for Ivy repos only.
Feel free to send this project a pull req or take over.

**Comment by pdalpra** [comment]
Sure, I'll try to find a way to make both Ivy and Maven happy and send a PR.
Would you mind if I add a boolean Setting to your plugin to flag that it should be "Maven-friendly" ?

Or I could try to rely on the `publishMavenStyle` setting : after all, if somebody publishes artifacts "Maven style", it's not crazy to think he wants to publish to a Maven repo after all.

**Comment by eed3si9n** [comment]
I think `publishMavenStyle` is fine, at least for the first try.

**Comment by pdalpra** [comment]
One small question before working on it extensively : would you mind if I migrate the plugin to use the `.value` macro instead of using the `<<=` operator ?
Maybe a personal preference, but I find using the `.value` macro leading to a way more readable build/plugin definition ;)

**Comment by eed3si9n** [comment]
I'd expect any new development to use sbt 0.13 `.value` style. The current code base predates it.
